version: '3.3'
services:  
  app:
    image: richavarma/mlops_repo:latest
    command: >
      sh -c "python app.py wait_for_mysqldb &&
             python social_distance_det.py &&
             python main.py"
    environment:
      - DISPLAY=:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    depends_on:
      - mysqldb
    ports:
      - "5000:5000"
    
  mysqldb:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "5423:5423"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    tty: true

