version: '3.7'
services:  
  app:
    image: richavarma/mlops_repo:latest
    command: >
      sh -c "python app.py wait_for_db &&
             python social_distance_det.py &&
             python main.py runserver 0.0.0.0:5000"
    depends_on:
      - mysqldb
    ports:
      - "5000:5000"
    networks:
      - turingmysql
    
  mysqldb:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - turingmysql
    ports:
      - "5423:5423"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    tty: true

networks:
  turingmysql: