version: '3.3'
services:  
  app:
    image: richavarma/mlops_repo:latest
    command: >
      sh -c "python app.py wait_for_db &&
             python social_distance_det.py &&
             python main.py runserver 0.0.0.0:5002"
    links:
      - db
    ports:
      - "5002:5002"
  
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "./db:/docker-entrypoint-initdb.d/:ro"
      - "./myvol:/var/lib/mysql"
